eureka:
  instance:
    health-check-url-path: /actuator/health
    hostname: localhost
    #hostname: 172.31.25.120
    #hostname: 3.17.57.215
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      startup: ${random.int}
    port: 8761
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  boot:
    admin:
      client:
        url: http://localhost:8760
  # Datasource properties
  datasource:
    continue-on-error: true
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    password: postgres
    platform: postgres
    #url: jdbc:postgresql://localhost:5432/acesso-service
    url: jdbc:postgresql://db-microservices.ci347vo4wg5v.us-east-2.rds.amazonaws.com:5432/acesso-service
    username: postgres
    # JPA Properties
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
