eureka:
  instance:
    health-check-url-path: /actuator/health
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      startup: ${random.int}
    port: 8761
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
      
spring:
  boot:
    admin:
      client:
        url: http://localhost:8760
