spring:
  datasource:
    continue-on-error: true
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    password: postgres
    platform: postgres
    url: jdbc:postgresql://localhost:5432/auth-server
    username: postgres
    # JPA Properties
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
