server:
    port: 9093

eureka:
    instance:
        hostname: localhost
        port: 9091
    client:
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
        server:
            wait-time-in-ms-when-sync-empty: 3000

authserver:
    hostname: http://localhost:9092
security:
    oauth2:
        resource:
            userInfoUri: ${authserver.hostname}/user

spring:
    datasource:
        continue-on-error: true
        driver-class-name: org.postgresql.Driver
        initialization-mode: always
        password: postgres
        platform: postgres
        url: jdbc:postgresql://localhost:5432/order-service
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: create
        show-sql: true
