server:
  port: 8761

eureka:
  instance:
    health-check-url-path: /actuator/health
    hostname: localhost
    #hostname: 172.31.25.120
    #hostname: 3.17.57.215
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      startup: ${random.int}
  client:
    fetchRegistry: false
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
    
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS

spring:
  boot:
    admin:
      client:
        url: http://localhost:8760
