server:
  port: 9000
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
#  thymeleaf:
#    mode: HTML
#    cache: false
  

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000
